In [2]:
import pandas as pd 
import torch

In [2]:
raw_data = pd.read_csv("data/raw/processed_normalized_full_data_with_features.csv", index_col=[0])
# horse_history = pd.read_csv("data/raw/processed_normalized_full_data_with_horse_history.csv", index_col=[0])
# indexes = pd.read_csv("data/raw/fff.csv", index_col=[0])

In [35]:
raw_data

                        horse_weight  horse_win_percents  jockey_win_percent  \
date_race_id horse_ids
0            708440        -1.226796           -0.572114           -1.180502
             714689        -0.480057           -0.572114           -1.180502
             716693        -1.023140           -0.572114           -1.180502
             718346        -1.023140           -0.572114           -1.180502
             744226        -1.023140           -0.572114           -1.180502
...                              ...                 ...                 ...
188852       1967629       -0.208516            0.380401           -1.180502
             2394811        0.063025            2.285432            1.154250
             2394827       -0.276401           -0.572114           -0.013126
             2829590       -0.276401           -0.572114           -0.013126
             2852529        0.063025            4.190464            0.570562

                        trainer_win_percent  days_since_last_race  \
date_race_id horse_ids
0            708440               -1.041915              2.715619
             714689               -1.041915              2.715619
             716693               -1.041915              2.715619
             718346               -1.041915              2.715619
             744226               -1.041915              2.715619
...                                     ...                   ...
188852       1967629               1.016550             -0.259694
             2394811               3.589631             -0.210137
             2394827               2.045782             -0.210137
             2829590              -1.041915             -0.397881
             2852529               0.501933             -0.251117

                        mean_speed_figures  last_figures  best_figures_dist  \
date_race_id horse_ids
0            708440              -1.596847     -1.312069          -1.058975
             714689              -1.596847     -1.312069          -1.058975
             716693              -1.596847     -1.312069          -1.058975
             718346              -1.596847     -1.312069          -1.058975
             744226              -1.596847     -1.312069          -1.058975
...                                    ...           ...                ...
188852       1967629              0.808756      1.755201           1.346267
             2394811              0.760365      1.477447           1.254591
             2394827              0.151846     -0.075208           0.796459
             2829590              0.625851      0.819542           0.956805
             2852529              0.921602     -0.127840          -1.058975

                        best_figures_going  top_speeds  ...  draws__35  \
date_race_id horse_ids                                  ...
0            708440              -1.334018   -1.028010  ...          0
             714689              -1.334018   -1.165406  ...          0
             716693              -1.334018   -0.780698  ...          0
             718346              -1.334018   -1.165406  ...          0
             744226              -1.334018   -1.522635  ...          0
...                                    ...         ...  ...        ...
188852       1967629              1.417530    0.208551  ...          0
             2394811              1.168366    0.153593  ...          0
             2394827              0.578181    0.181072  ...          0
             2829590              0.743433   -1.522635  ...          0
             2852529             -1.334018    0.400905  ...          0

                        draws__36  draws__43  draws__78  draws__81  \
date_race_id horse_ids
0            708440             0          0          0          0
             714689             0          0          0          0
             716693             0          0          0          0
             718346             0          0          0          0
             744226             0          0          0          0
...                           ...        ...        ...        ...
188852       1967629            0          0          0          0
             2394811            0          0          0          0
             2394827            0          0          0          0
             2829590            0          0          0          0
             2852529            0          0          0          0

                        draws__101  draws__141  race_type__0  race_type__1  \
date_race_id horse_ids
0            708440              0           0             0             1
             714689              0           0             0             1
             716693              0           0             0             1
             718346              0           0             0             1
             744226              0           0             0             1
...                            ...         ...           ...           ...
188852       1967629             0           0             0             1
             2394811             0           0             0             1
             2394827             0           0             0             1
             2829590             0           0             0             1
             2852529             0           0             0             1

                        race_type__2
date_race_id horse_ids
0            708440                0
             714689                0
             716693                0
             718346                0
             744226                0
...                              ...
188852       1967629               0
             2394811               0
             2394827               0
             2829590               0
             2852529               0

[1868438 rows x 178 columns]

In [4]:
horse_history

,horse_ids,race_age,horse_weight,horse_win_percents,jockey_win_percent,trainer_win_percent,days_since_last_race,mean_speed_figures,last_figures,best_figures_dist,...,draws__33,draws__34,draws__35,draws__36,draws__78,draws__101,race_type__0,race_type__1,race_type__2,race_id
0,697748,36,-1.452532,-0.623191,-1.203847,-1.068080,-0.574134,-0.910764,-0.692034,-0.477036,...,0,0,0,0,0,0,0,1,0,495896.0
1,659459,14,-1.047134,-0.623191,-1.203847,-1.068080,-0.574134,-0.243193,-0.184764,-1.223823,...,0,0,0,0,0,0,0,1,0,495904.0
2,720756,14,-1.182267,-0.623191,-1.203847,-1.068080,-0.564824,-0.206105,-0.156582,-1.223823,...,0,0,0,0,0,0,0,1,0,496239.0
3,734395,7,-1.655232,-0.623191,-1.203847,-1.068080,-0.555515,-1.318724,-1.002032,-0.733744,...,0,0,0,0,0,0,0,1,0,496380.0
4,738636,30,-0.303904,-0.623191,-1.203847,-0.544836,-0.555515,-0.057756,-0.043855,-1.223823,...,0,0,0,0,0,0,0,1,0,496375.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647142,3181207,29,-0.506603,0.291478,-0.613433,-1.068080,1.120185,-0.073807,0.266143,-1.223823,...,0,0,0,0,0,0,0,1,0,783217.0
1647143,3119662,29,-0.506603,0.748813,1.748224,0.501653,1.446015,-0.539891,0.040690,-1.223823,...,0,0,0,0,0,0,0,1,0,783217.0
1647144,3102082,29,-0.506603,1.206147,1.157810,2.071386,1.194660,0.065868,0.688868,-1.223823,...,0,0,0,0,0,0,0,1,0,783217.0
1647145,3198779,29,-0.506603,1.206147,-0.023019,1.548142,0.803664,0.575565,0.237961,-1.223823,...,0,0,0,0,0,0,0,1,0,783217.0
1647146,3208528,29,-0.506603,1.206147,-0.023019,0.501653,1.101566,0.822814,0.688868,-1.223823,...,0,0,0,0,0,0,0,1,0,783217.0

In [44]:
indexes

          race_id  horse_ids  date_race_id
279      495896.0     697748            15
479      495904.0     659459            28
671      496239.0     720756            47
736      496380.0     734395            39
700      496375.0     738636            47
...           ...        ...           ...
1868062  783217.0    3198779        180120
1868062  783217.0    3198779        182463
1868056  783217.0    3208528        177966
1868056  783217.0    3208528        180670
1868056  783217.0    3208528        180758

[20797669 rows x 3 columns]

In [47]:
indexes.reset_index()['horse_ids'].unique().shape

(170569,)

In [9]:
raw_data = raw_data.set_index(["date_race_id", "horse_ids"])
horse_history = horse_history.set_index(
    ["date_race_id", "horse_ids"])
indexes = indexes.set_index(
    ["race_id", "horse_ids"])

In [10]:
raw_data = raw_data.sort_index()
horse_history = horse_history.sort_index()
indexes = indexes.sort_index()

In [19]:
horse = horse_history.iloc[1000000]

In [20]:
hist = indexes.loc[(
                horse.race_id, horse.name[1])]['date_race_id'].values
idxs = [(x, horse.name[1]) for x in hist]
x_data = torch.tensor(
                raw_data.loc[raw_data.index.isin(idxs)].values.astype('float64'))

In [41]:
horse

race_age                   14.000000
horse_weight                1.993353
horse_win_percents          3.035486
jockey_win_percent         -0.613433
trainer_win_percent         1.024898
                           ...
draws__101                  0.000000
race_type__0                0.000000
race_type__1                0.000000
race_type__2                1.000000
race_id                665320.000000
Name: (116057, 903432), Length: 180, dtype: float64

In [30]:
indexes['date_race_id']

race_id   horse_ids
253375.0  708201         2049
          708201         2693
          708201         3335
          708201         6327
          708201         7494
                        ...
783410.0  2219533      167645
          2219533      168903
          2219533      169817
          3093289      171795
          3093289      179840
Name: date_race_id, Length: 20797669, dtype: int64

In [23]:
x_data.shape

torch.Size([3, 178])

In [9]:
rd = ab

In [10]:
rd['offset_horse_id'] = pd.factorize(rd['horse_ids'])[0]

KeyError: 'horse_ids'

In [ ]:
rd['num_previous_races'] = rd.groupby('offset_horse_id').cumcount()

In [ ]:
fd = rd.loc[rd.num_previous_races != 0]

In [11]:
srd = rd.sort_values(by=['offset_horse_id', 'date_race_id'])

KeyError: 'date_race_id'

In [8]:
srd = srd.drop(['index','horse_ids', 'date_race_id'], axis=1)

In [11]:
#srd.to_csv("data/full_features.csv")

In [14]:
ssrd = torch.tensor(rd.values)

In [21]:
num_previous_races = torch.tensor(srd['num_previous_races'].values)

In [31]:
ssrd[100:101]

tensor([[ 9.7515e+05,  1.3091e-01,  3.8040e-01,  5.7056e-01, -5.2730e-01,
         -4.0932e-01,  5.1318e-01,  1.0332e+00,  6.5902e-01,  1.2982e+00,
         -1.5226e+00, -1.8585e+00,  7.8282e-01,  3.6442e-01,  7.1344e-02,
         -7.7768e-02, -1.4900e+00,  8.7694e-01,  4.5273e-01,  1.0772e+00,
          1.5546e+00, -4.5267e-01,  1.4865e+00,  1.1090e+00, -4.2688e-01,
          3.2565e+00, -9.4595e-01,  1.2722e-01,  0.0000e+00, -2.6787e-01,
         -1.6104e+00, -3.1641e-01, -4.1977e-01, -2.5700e-01, -4.7084e-01,
         -2.6787e-01, -1.6104e+00, -3.1641e-01, -4.1977e-01, -2.5700e-01,
         -4.7084e-01,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  3.0000e+00,
          4.1000e+01]], dtype=torch.float64)

:

In [29]:
ssrd[99:100]

tensor([[ 9.6893e+05,  1.6923e+00,  3.8040e-01, -1.1805e+00, -1.0419e+00,
         -1.6153e-01,  6.4268e-01,  5.7715e-01,  1.3793e+00,  1.2982e+00,
          9.2624e-01,  5.0473e-03,  8.1540e-01, -2.7762e-01,  5.7993e-02,
          8.6945e-02, -4.1863e-01,  6.6651e-01, -3.6721e+00,  1.3985e+00,
          1.5546e+00,  1.1879e-02,  1.5734e+00,  1.7171e+00,  6.5566e-02,
          1.0497e-01, -9.4595e-01,  1.2722e-01,  0.0000e+00, -2.6787e-01,
         -1.6104e+00, -3.1641e-01, -4.1977e-01, -2.5700e-01, -4.7084e-01,
         -2.6787e-01, -1.6104e+00, -3.1641e-01, -4.1977e-01, -2.5700e-01,
         -4.7084e-01,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00,  3.0000e+00,
          4.0000e+01]], dtype=torch.float64)

In [3]:
ab = pd.read_csv("data/full_features.csv")

In [7]:
ab.drop(['num_previous_races', 'offset_horse_id'], axis=1)

,Unnamed: 0,horse_weight,horse_win_percents,jockey_win_percent,trainer_win_percent,days_since_last_race,mean_speed_figures,last_figures,best_figures_dist,best_figures_going,...,draws__35,draws__36,draws__43,draws__78,draws__81,draws__101,draws__141,race_type__0,race_type__1,race_type__2
0,0,-1.023140,-0.572114,-1.180502,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
1,7883,-1.430451,5.142979,-1.180502,1.531166,-0.392163,-0.732108,-0.601532,-1.058975,-0.696619,...,0,0,0,0,0,0,0,0,1,0
2,30250,-0.412172,2.285432,-0.596814,1.531166,-0.367385,-0.315753,0.082689,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
3,33900,-1.362566,1.332917,-0.566094,-0.012683,-0.416942,-0.742784,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
4,41525,-0.547943,0.856659,-0.013126,-0.527299,-0.412176,-0.700081,-0.469951,-1.058975,-0.578582,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868433,1868393,-0.140631,-0.572114,-0.596814,0.501933,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
1868434,1868394,-0.140631,-0.572114,-0.013126,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
1868435,1868395,-0.480057,-0.572114,-0.596814,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
1868436,1868400,-0.344287,-0.572114,-0.596814,0.501933,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,0,1,0
1868437,1868437,1.352846,-0.572114,0.570562,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,0,1,0,0

In [6]:
ab

,Unnamed: 0,horse_weight,horse_win_percents,jockey_win_percent,trainer_win_percent,days_since_last_race,mean_speed_figures,last_figures,best_figures_dist,best_figures_going,...,draws__43,draws__78,draws__81,draws__101,draws__141,race_type__0,race_type__1,race_type__2,offset_horse_id,num_previous_races
0,0,-1.023140,-0.572114,-1.180502,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,0,0
1,7883,-1.430451,5.142979,-1.180502,1.531166,-0.392163,-0.732108,-0.601532,-1.058975,-0.696619,...,0,0,0,0,0,0,1,0,0,1
2,30250,-0.412172,2.285432,-0.596814,1.531166,-0.367385,-0.315753,0.082689,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,0,2
3,33900,-1.362566,1.332917,-0.566094,-0.012683,-0.416942,-0.742784,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,0,3
4,41525,-0.547943,0.856659,-0.013126,-0.527299,-0.412176,-0.700081,-0.469951,-1.058975,-0.578582,...,0,0,0,0,0,0,1,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868433,1868393,-0.140631,-0.572114,-0.596814,0.501933,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,221286,0
1868434,1868394,-0.140631,-0.572114,-0.013126,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,221287,0
1868435,1868395,-0.480057,-0.572114,-0.596814,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,221288,0
1868436,1868400,-0.344287,-0.572114,-0.596814,0.501933,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,0,1,0,221289,0
1868437,1868437,1.352846,-0.572114,0.570562,-1.041915,2.715619,-1.596847,-1.312069,-1.058975,-1.334018,...,0,0,0,0,0,1,0,0,221290,0