In [3]:
import pandas as pd

In [21]:
df = pd.read_csv("data/raw/full_data_with_features.csv")

In [22]:
horse_grouped = df.groupby('horse_ids')['date_race_id'].apply(list).to_dict()
def dothis(row):
  fl = horse_grouped[row['horse_ids']]
  return fl[:fl.index(row['date_race_id'])]

# list(df.loc[(df.horse_ids == row.horse_ids) & (df.date < row.date)]['race_id'])

In [23]:
#indexes_of_races_for_horse 
horse_history = pd.DataFrame(index=df.index)
horse_history['race_id'] = df['race_id']
horse_history['horse_ids'] = df['horse_ids']
horse_history['old_races'] = df.apply(dothis, axis=1)

In [115]:
new_df = raw_data.merge(horse_history[['race_id','horse_ids','old_races']], on=['race_id','horse_ids']).iloc[: , 1:]

In [25]:
horse_hist.loc[(new_df.race_id == 495896.0) & (new_df.horse_ids == 697748)]

NameError: name 'horse_hist' is not defined

In [116]:
new_df.dtypes

horse_ids       int64
track_id      float64
race_class      int64
distance      float64
going           int64
               ...
dist__37.0      uint8
dist__38.0      uint8
dist__39.0      uint8
dist__40.0      uint8
old_races      object
Length: 100, dtype: object

In [36]:
new_df = new_df[new_df.old_races.astype('bool')].drop('old_races', axis=1)
new_df

,race_id,horse_ids,track_id,race_class,distance,going,race_age,race_handicap,race_type,date,...,sire_prog_type_win_percent,sire_og_dist_win_percent,sire_prog_dist_win_percent,dam_og_going_win_percent,dam_prog_going_win_percent,dam_og_type_win_percent,dam_prog_type_win_percent,dam_og_dist_win_percent,dam_prog_dist_win_percent,date_race_id
352,495896.0,697748,394.0,5,1760.0,18,36,False,1,2010-01-02,...,0.104999,0.000000,0.100667,0.000000,0.093398,0.000000,0.104999,0.000000,0.100667,40
577,495904.0,659459,1079.0,4,1540.0,16,14,True,1,2010-01-03,...,0.099361,0.000000,0.106195,0.000000,0.099183,0.000000,0.099361,0.000000,0.106195,61
628,496239.0,720756,513.0,5,1870.0,16,14,True,1,2010-01-04,...,0.086893,0.000000,0.085873,0.000000,0.092274,0.000000,0.086893,0.000000,0.085873,68
703,496380.0,734395,394.0,5,1320.0,18,7,True,1,2010-01-05,...,0.095167,0.000000,0.090389,0.000000,0.074332,0.000000,0.095167,0.000000,0.090389,78
739,496375.0,738636,394.0,4,1320.0,18,30,False,1,2010-01-05,...,0.081282,0.000000,0.082892,0.000000,0.080745,0.000000,0.081282,0.000000,0.082892,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868432,783217.0,3181207,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.085921,0.000000,0.080569,0.066667,0.077670,0.107143,0.085921,0.000000,0.080569,188851
1868433,783217.0,3119662,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.133333,0.333333,0.500000,0.444444,0.100000,0.333333,0.133333,0.333333,0.500000,188851
1868434,783217.0,3102082,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.175084,0.857143,0.196970,0.000000,0.158621,0.818182,0.175084,0.857143,0.196970,188851
1868435,783217.0,3198779,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.119587,0.500000,0.128854,0.500000,0.111013,0.600000,0.119587,0.500000,0.128854,188851
1868436,783217.0,3208528,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.040000,0.666667,0.000000,0.000000,0.000000,0.571429,0.040000,0.666667,0.000000,188851

In [118]:
new_df.to_csv("data/raw/processed_full_data_with_horse_history.csv")

In [9]:
histories = horse_history.explode('date_race_id')

In [10]:
import numpy as np

In [14]:
horse_hist = histories.dropna()

In [1]:
df

NameError: name 'df' is not defined

In [15]:
horse_hist

          race_id  horse_ids date_race_id
279      495896.0     697748           15
479      495904.0     659459           28
671      496239.0     720756           47
736      496380.0     734395           39
700      496375.0     738636           47
...           ...        ...          ...
1868062  783217.0    3198779       180120
1868062  783217.0    3198779       182463
1868056  783217.0    3208528       177966
1868056  783217.0    3208528       180670
1868056  783217.0    3208528       180758

[20797669 rows x 3 columns]

In [12]:
pd.merge(histories[:1000], df[:1000], how='left', left_on=['horse_ids','date_race_id'], right_on=['horse_ids','race_id'])

,race_id_x,horse_ids,date_race_id_x,race_id_y,track_id,race_class,distance,going,race_age,race_handicap,...,sire_prog_type_win_percent,sire_og_dist_win_percent,sire_prog_dist_win_percent,dam_og_going_win_percent,dam_prog_going_win_percent,dam_og_type_win_percent,dam_prog_type_win_percent,dam_og_dist_win_percent,dam_prog_dist_win_percent,date_race_id_y
0,495885.0,716693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,496991.0,674407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,496991.0,699630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,496991.0,693632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,496991.0,660606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,497347.0,728645,39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,497641.0,749581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,497609.0,601548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,497641.0,749582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,497641.0,749579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def doit(row):
    new_row = df.loc[(df.date_race_id== row.date_race_id) & (df.horse_ids == row.horse_ids)].values
    if len(new_row) == 0:
        return pd.Series(np.zeros(len(df.columns)), index=df.columns)
    new_row = new_row[0]
    return pd.Series(new_row, index=df.columns)

In [18]:
horse_hist

          race_id  horse_ids date_race_id
279      495896.0     697748           15
479      495904.0     659459           28
671      496239.0     720756           47
736      496380.0     734395           39
700      496375.0     738636           47
...           ...        ...          ...
1868062  783217.0    3198779       180120
1868062  783217.0    3198779       182463
1868056  783217.0    3208528       177966
1868056  783217.0    3208528       180670
1868056  783217.0    3208528       180758

[20797669 rows x 3 columns]

In [17]:
fff = horse_hist.to_csv("fff.csv")

In [45]:
df = df.set_index(["race_id","horse_ids"])

In [61]:
max_length = max(raw_data['length'])
max_places = max(raw_data['places']) + 1

In [95]:
raw_data.loc[(raw_data.length == 0) & (raw_data.won == 0), 'length'] = max_length
raw_data.loc[(raw_data.places == 0) & (raw_data.won == 0), 'places'] = max_places

In [96]:
going_dummy = pd.get_dummies(raw_data['going_cat'].astype("category"), prefix="going_")
pedigree_dummy = pd.get_dummies(raw_data['pedigree_info'].astype("category"), prefix="pedigree_")
distance_dummy = pd.get_dummies(raw_data['dist_categories'].astype("category"), prefix="dist_")

In [97]:
raw_data = raw_data.merge(going_dummy, left_index=True, right_index=True)
raw_data = raw_data.merge(distance_dummy, left_index=True, right_index=True)
#raw_data = raw_data.merge(pedigree_dummy, left_index=True, right_index=True)
raw_data = raw_data.drop(["going_cat", "dist_categories", "pedigree_info"], axis=1)

In [107]:
raw_data = raw_data.drop(['date'], axis=1)

In [114]:
raw_data.to_csv("processed_full_data_with_features.csv")

In [53]:
df.loc[(495885.0, 716693)]

track_id                        394.0
race_class                          5
distance                       2420.0
going                              18
race_age                           32
                               ...
dam_og_type_win_percent           0.0
dam_prog_type_win_percent    0.055738
dam_og_dist_win_percent           0.0
dam_prog_dist_win_percent    0.070175
date_race_id                        0
Name: (495885.0, 716693), Length: 62, dtype: object

In [2]:
from torch.utils.data import Dataset, DataLoader
import torch

c:\Users\leish\anaconda3\envs\tf3\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [61]:
new_df.loc[(new_df.date_race_id == 15)]

Empty DataFrame
Columns: [race_id, horse_ids, track_id, race_class, distance, going, race_age, race_handicap, race_type, date, draws, horse_ages, horse_weight, horse_win_percents, jockey_ids, jockey_win_percent, trainer_ids, trainer_win_percent, days_since_last_race, mean_speed_figures, last_figures, best_figures_dist, best_figures_going, top_speeds, ratings, official_ratings, odds, places, won, days, mean_ratings, last_ratings, last_official_rating, difference_in_ratings, going_cat, best_rating_going, best_official_rating_going, win_percent_going, dist_categories, best_rating_dist, best_official_rating_dist, win_percent_dist, placed, length, pedigree_info, sire_id, dam_id, dam_sire_id, sire_win_percent, dam_win_percent, dam_sire_win_percent, sire_og_going_win_percent, sire_prog_going_win_percent, sire_og_type_win_percent, sire_prog_type_win_percent, sire_og_dist_win_percent, sire_prog_dist_win_percent, dam_og_going_win_percent, dam_prog_going_win_percent, dam_og_type_win_percent, dam_prog_type_win_percent, dam_og_dist_win_percent, dam_prog_dist_win_percent, date_race_id]
Index: []

[0 rows x 64 columns]

In [94]:
raw_data = pd.read_csv("data/raw/full_data_with_features.csv", index_col=[0])
filtered_data = pd.read_csv("data/raw/full_data_with_horse_history.csv", index_col=[0])
index_file = pd.read_csv("data/raw/fff.csv", index_col=[0])

In [11]:
filtered_data

,race_id,horse_ids,track_id,race_class,distance,going,race_age,race_handicap,race_type,date,...,sire_prog_type_win_percent,sire_og_dist_win_percent,sire_prog_dist_win_percent,dam_og_going_win_percent,dam_prog_going_win_percent,dam_og_type_win_percent,dam_prog_type_win_percent,dam_og_dist_win_percent,dam_prog_dist_win_percent,date_race_id
352,495896.0,697748,394.0,5,1760.0,18,36,False,1,2010-01-02,...,0.104999,0.000000,0.100667,0.000000,0.093398,0.000000,0.104999,0.000000,0.100667,40
577,495904.0,659459,1079.0,4,1540.0,16,14,True,1,2010-01-03,...,0.099361,0.000000,0.106195,0.000000,0.099183,0.000000,0.099361,0.000000,0.106195,61
628,496239.0,720756,513.0,5,1870.0,16,14,True,1,2010-01-04,...,0.086893,0.000000,0.085873,0.000000,0.092274,0.000000,0.086893,0.000000,0.085873,68
703,496380.0,734395,394.0,5,1320.0,18,7,True,1,2010-01-05,...,0.095167,0.000000,0.090389,0.000000,0.074332,0.000000,0.095167,0.000000,0.090389,78
739,496375.0,738636,394.0,4,1320.0,18,30,False,1,2010-01-05,...,0.081282,0.000000,0.082892,0.000000,0.080745,0.000000,0.081282,0.000000,0.082892,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868432,783217.0,3181207,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.085921,0.000000,0.080569,0.066667,0.077670,0.107143,0.085921,0.000000,0.080569,188851
1868433,783217.0,3119662,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.133333,0.333333,0.500000,0.444444,0.100000,0.333333,0.133333,0.333333,0.500000,188851
1868434,783217.0,3102082,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.175084,0.857143,0.196970,0.000000,0.158621,0.818182,0.175084,0.857143,0.196970,188851
1868435,783217.0,3198779,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.119587,0.500000,0.128854,0.500000,0.111013,0.600000,0.119587,0.500000,0.128854,188851
1868436,783217.0,3208528,193.0,-1,2200.0,4,29,False,1,2021-04-25,...,0.040000,0.666667,0.000000,0.000000,0.000000,0.571429,0.040000,0.666667,0.000000,188851

In [113]:
val = raw_data.loc[(raw_data.date_race_id == 15) & (raw_data.horse_ids == 697748)].values[0]
val = val.astype("float64")
torch.tensor(val)

tensor([4.9589e+05, 6.9775e+05, 3.9400e+02, 5.0000e+00, 1.7600e+03, 1.8000e+01,
        1.4000e+01, 1.0000e+00, 1.0000e+00, 9.0000e+00, 9.0000e+00, 1.1800e+02,
        0.0000e+00, 7.9015e+04, 0.0000e+00, 1.5948e+04, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 3.2000e+01, 4.2000e+01,
        4.7000e+01, 2.1000e+01, 5.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 7.7500e+00, 5.7272e+05,
        5.4304e+05, 9.9943e+04, 1.0690e-01, 1.1111e-01, 0.0000e+00, 0.0000e+00,
        9.3398e-02, 0.0000e+00, 1.0500e-01, 0.0000e+00, 1.0067e-01, 0.0000e+00,
        9.3398e-02, 0.0000e+00, 1.0500e-01, 0.0000e+00, 1.0067e-01, 1.5000e+01,
        0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00], dtype=torch.float64)

In [119]:
class HorseHistoryDataset(Dataset):
    def __init__(self, raw_data_file , filtered_data_file,  index_file, transform=None) -> None:
        self.raw_data = pd.read_csv(raw_data_file, index_col=[0])
        self.filtered_data = pd.read_csv(filtered_data_file, index_col=[0])
        self.horse_history_index = pd.read_csv(index_file, index_col=[0])

        self.raw_data = self.raw_data.set_index(["date_race_id", "horse_ids"])
        self.filtered_data = self.filtered_data.set_index(["date_race_id", "horse_ids"])
        self.horse_history_index = self.horse_history_index.set_index(["race_id", "horse_ids"])   

        print(self.raw_data.head())
        print(self.filtered_data.head())
        print(self.horse_history_index.head())

        self.transform=transform

    def __len__(self) -> int:
        return len(self.raw_data)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        horse = self.filtered_data.iloc[idx]
        if self.transform:
            pass 

        try: 
            print(idx, horse.race_id, horse.name)
            hist = self.horse_history_index.loc[(horse.race_id, horse.name[1])]
            print(hist)
            print(hist.date_race_id.values, horse.name[1])
            x_data = torch.tensor(self.raw_data.loc[(hist.date_race_id.values[0], horse.name[1])].values.astype('float64'))
            print(x_data)
            # Gets the horse race that is currently occuring. Will be predicting the track stats too
            # Could just extract 'won' variable
            y_data = torch.tensor(horse.values.astype('float64'))
            print(y_data)
        except KeyError as e:
            print("Key Error")
            return None
        
        return x_data, y_data
    
tl = DataLoader(HorseHistoryDataset("data/raw/processed_full_data_with_features.csv", "data/raw/processed_full_data_with_horse_history.csv", "data/raw/fff.csv"), batch_size=32)

KeyboardInterrupt:

In [35]:
train_features, train_labels = next(iter(tl))
train_features, train_labels

0 495896.0 (40, 697748)

C:\Users\leish\AppData\Local\Temp\ipykernel_16092\1223039575.py:30: PerformanceWarning: indexing past lexsort depth may impact performance.
  hist = self.horse_history_index.loc[(horse.race_id, horse.name[1])]

                    date_race_id
race_id  horse_ids
495896.0 697748               15
[15] 697748

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.